language: node_js
node_js:
  - "v14.4.0"

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  domain: https://shaikh-spacex-app.surge.sh/
  project: ./build/

on:
  branch: master
